java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\300\300.txt > 300.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\300\301.txt > 301.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\300\302.txt > 302.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\300\303.txt > 303.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\300\304.txt > 304.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\400\400.txt > 400.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\400\401.txt > 401.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\400\402.txt > 402.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\400\403.txt > 403.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\400\404.txt > 404.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\500\500.txt > 500.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\500\501.txt > 501.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\500\502.txt > 502.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\500\503.txt > 503.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\500\504.txt > 504.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\600\600.txt > 600.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\600\601.txt > 601.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\600\602.txt > 602.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\600\603.txt > 603.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\600\604.txt > 604.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\700\700.txt > 700.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\700\701.txt > 701.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\700\702.txt > 702.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\700\703.txt > 703.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\700\704.txt > 704.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\800\800.txt > 800.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\800\801.txt > 801.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\800\802.txt > 802.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\800\803.txt > 803.txt
java -jar --enable-preview annealingfeasible.jar C:\Users\Philip\Documents\programmieren\python\bwinf41-2\weniger-krumme-touren\beispiele\random\800\804.txt > 804.txt